version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: legacoee
    ports:
      - "9001:9001"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    environment:
      NODE_ENV: development
    restart: always
